server:
  port: 9101

spring:
  application:
    name: portal-ebank-individual
  cloud:
    loadbalancer:
      ribbon:
        # disable Spring Cloud Netflix Ribbon to enable Spring Cloud LoadBalancer
        enabled: false

logging:
  level:
    org.springframework: debug
