server:
  port: 9090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: oauth_token
          uri: http://127.0.0.1:8000
          predicates:
            - Path=/oauth/token
            - Header=Authorization, .*
        - id: eBank_individual
          uri: http://localhost:9101
          predicates:
            - Path=/ebank/**
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 2

management:
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework: debug
