server:
  port: 9090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: retry_test
          uri: lb://portal-ebank-individual
          predicates:
            - Path=/ebank/**
          filters:
            - name: Retry
              args:
                retries: 3
#                series:
#                  - SERVER_ERROR
#                  - CLIENT_ERROR
                statuses:
                  - BAD_GATEWAY
                  - INTERNAL_SERVER_ERROR
                  - NOT_FOUND
                methods: GET,POST
                exceptions:
                  - java.io.IOException
                  - java.net.ConnectException
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

management:
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework: info
logging.level.org.springframework.cloud.gateway.filter.factory: TRACE
