server:
  port: 9090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: oauth_token
          uri: http://127.0.0.1:8000
          predicates:
            - Path=/oauth/token
            - Header=Authorization, .*
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
            methods: GET,POST
            backoff:
              firstBackoff: 10ms
              maxBackoff: 50ms
              factor: 2
              basedOnPreviousValue: false

management:
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework: debug
